### ISSUE TITLE
cannot see t411 plugin on couchpotato Searcher page

### ISSUE THREAD

**Issue by joannblaz** [djoole/couchpotato.provider.t411#1]
Hello,

I created a quork directory inside my custom_plugins and put the init.py and main.py files inside it.
I tried rebooting couchpotato and refreshing the dedicated page, but I am surely missing something here.
Can you please let me know if I have skipped a step?

**Comment by djoole** [comment]
My mistake, the folder needs to be named t411 and not quorks

**Comment by joannblaz** [comment]
Works ! Tx !
