### ISSUE TITLE
Can't get it to work.

### ISSUE THREAD

**Issue by phathak** [djoole/couchpotato.provider.t411#10]
Hi! I've tried adding T411 as a provider to couchpotato and CouchPotatoServer but never got it working. Is it still working? I follow the instructions and then restart couchpotato but it never appears in the torrent providers list...

**Comment by djoole** [comment]
Hi, I haven't used it since quite a time, I'll have a look and let you know.

**Comment by djoole** [comment]
Hi, I've just checked and everything is working just fine for me.
Did you put the t411 folder in your custom_plugins folder?
What Couchpotato branch are you using?

**Comment by phathak** [comment]
Thanks for taking the time!

Yes I have put the t411 folder into the custom_plugins folder. 
Right now I'm using the official release of couchpotato, version 2.6.3. I've tried with a bunch of different ones but kinda get lost. Which one are you using? Maybe 
I could start fresh with yours and this could work?

**Comment by djoole** [comment]
I'm using the latest source from master branch from https://github.com/RuudBurger/CouchPotatoServer
Please post your debug logs, from CP init, so that i can see why it's not loading the plugin.

**Comment by phathak** [comment]
I'm now using RuudBurger's master branch and the provider has appeared in the settings. It looks like it's working as intended because i'm not getting any errors. Thanks!,

**Comment by djoole** [comment]
no problem :)

**Comment by phathak** [comment]
One last thing. I noticed the t411 provider appears in the searchers when couch potato is launched through terminal using this command : python /Applications/CouchPotatoServer/CouchPotato.py. I ported this one to port 5052.

BUT. When launched through a launchd command using this plist :

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>couchpotatoserver</string>
    <key>ProgramArguments</key>
    <array>
        <string>python</string>
        <string>/Applications/CouchPotatoServer/CouchPotato.py</string>
    </array>
</dict>
</plist>

I notice the couchpotato that is launched is not on the 5052 but rather on the default 5050 port AND the t411 provider is not there anymore. Looks like it's not launching the same way since it's exactly the same file.....

Thanks for your help.

**Comment by djoole** [comment]
It seems like you have more than one CP installed on your system and you're not launching the same...

**Comment by phathak** [comment]
I can assure you that I only have one instance of CP installed. Do you have a Mac? Could you test it with launchd?

**Comment by djoole** [comment]
My CP is on Freenas, not the same setup sorry.
But having port changed and custom providers disappear means that you launch your only CP instance with a different config dir.
In your launch shortcut you should add the option to point to a specific config dir, the one where you installed the provider.
