### ISSUE TITLE
Failed to parse t411

### ISSUE THREAD

**Issue by jujugrrr** [djoole/couchpotato.provider.t411#11]
Hi,
Thanks a lot for this plugin
None of the found files want to download though, I'm getting an encoding issue : 

```
07-25 22:21:55 INFO [core.media.movie.searcher] Search for 25th Hour in BR-Rip ignoring ETA
07-25 22:21:55 INFO [hpotato.core.plugins.base] Opening url: get https://www.t411.io/torrents/search/?search=(25th%20hour)%7C(La%2025e%20heure)%20brrip%7Cbdrip%7Chdtv%7Chdrip%7C(br%26rip), data: []
07-25 22:21:56 INFO [core.media.movie.searcher] Search for 25th Hour in DVD-Rip ignoring ETA
07-25 22:21:57 INFO [hpotato.core.plugins.base] Opening url: get https://www.t411.io/torrents/search/?search=(25th%20hour)%7C(La%2025e%20heure)%20dvdrip%7C(dvd%26rip), data: []
07-25 22:21:57 ERROR [                     t411] Failed to parse T411: Traceback (most recent call last):
  File "/apps/couchpotato2/data/custom_plugins/t411/main.py", line 105, in _searchOnTitle
    'name': replaceTitle(release_name, title, newTitle),
  File "/apps/couchpotato2/data/custom_plugins/t411/main.py", line 254, in replaceTitle
    log.debug('Replacing -- ' + newTitle.decode('ascii', errors='replace') + ' -- in the release -- ' + releaseName.decode('ascii', errors='replace') + ' -- by the original title -- ' + title.decode('ascii', errors='replace'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 5: ordinal not in range(128)
```

I'm using couch latest version (https://github.com/RuudBurger/CouchPotatoServer/tree/69825f9dbdfc42d5e6fcebd89828e21ff36330fa)

**Comment by jujugrrr** [comment]
Actually, it's the debugging line itself causing the problem. It looks good now :+1:

**Comment by djoole** [comment]
@clement-escolano pourrais-tu jeter un œil? Apparemment le debug de ta fonction replaceTitle poserait problème

**Comment by clement-escolano** [comment]
@djoole 
Coucou !
Oui il a l'air de ne pas bien marcher dans certains cas (j'avais regardé il y a un petit moment, c'était avec certaines versions de python, et pour les titres avec accent me semble-t-til).

Je n'ai pas accès à mon PC en ce moment, la seule chose qu'il y a à faire, c'est de commenter tous les log.debug :) Tu peux t'en occuper ? Ce n'est pas la meilleure solution mais au moins l'erreur n'apparaîtra plus. 
Je regarderai plus en détail l'encodage quand j'aurai mon PC, mais python et l'utf-8, c'est un vrai cauchemar...

**Comment by djoole** [comment]
OK tu as raison, on va pas se prendre la tête, c'est qu'un log de debug, j'ai suivi ton conseil je l'ai commenté.
Je referme du coup :)

**Comment by jujugrrr** [comment]
> Je n'ai pas accès à mon PC en ce moment, la seule chose qu'il y a à faire, c'est de commenter tous les log.debug :)

C'est ce que j'ai fais, c'est pour ca que j'ai ferme l'issue. :+1:
