### ISSUE TITLE
Error provider

### ISSUE THREAD

**Issue by D4rk56** [djoole/couchpotato.provider.t411#13]
### Information:

Providers I use: t411
Version of CouchPotato: source:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 13:06:41)
Running on: ...
### Logs:

```
07-27 15:56:39 ERROR [   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/home/couchpotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/home/couchpotato/couchpotato/core/media/_base/providers/base.py", line 220, in search
    self._searchOnTitle(title, media, quality, results)
  File "/home/couchpotato/custom_plugins/t411/main.py", line 70, in _searchOnTitle
    request = ('(' + title + ')|(' + newTitle + ')').replace(':', '')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)
encoding=ISO-8859-1 debug=False args=['--quiet', '--daemon', '--pid_file=/var/run/couchpotato/couchpotato.pid', '--data_dir=/home/couchpotato'] app_dir=/home/couchpotato data_dir=/home/couchpotato desktop=None options=Namespace(config_file='/home/couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/home/couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=True) 
```

**Comment by djoole** [comment]
Un problème d'encoding.
Je vais avoir besoin de savoir sur quel film tu as rencontré ce problème.

**Comment by D4rk56** [comment]
Ah mince je retrouve plus le nom du film en question, là avec les autres films ça marche correctement ..

**Comment by D4rk56** [comment]
Voilà un nom de film qui déclenche l'erreur : Batman v Superman: Dawn of Justice

**Comment by maxcore** [comment]
Tout les films avec des é è ê ë , comme le bug qui avait avec hd-o que tu as fixer ! Je crois que c'est le même bug..

**Comment by djoole** [comment]
Si c'est le même bug ça devrait aller vite :)
Je regarde ça!

**Comment by maxcore** [comment]
```
07-27 16:14:23DEBUG[                     t411] Looking for French title of : les associĂŠs
07-27 16:14:23ERROR[   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/volume1/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 220, in search
    self._searchOnTitle(title, media, quality, results)
  File "/usr/local/couchpotatoserver/var/custom_plugins/t411/main.py", line 67, in _searchOnTitle
    newTitle = getFrenchTitle(title)
  File "/usr/local/couchpotatoserver/var/custom_plugins/t411/main.py", line 210, in getFrenchTitle
    search = api.search(title)
  File "/usr/local/couchpotatoserver/var/custom_plugins/t411/allocine.py", line 66, in search
    response = self._do_request(params);
  File "/usr/local/couchpotatoserver/var/custom_plugins/t411/allocine.py", line 40, in _do_request
    sha1 = hashlib.sha1(self._secret_key+urllib.urlencode(params)+'&sed='+sed).digest()
  File "/usr/local/python/lib/python2.7/urllib.py", line 1347, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 10: ordinal not in range(128)

```

http://www.imdb.com/title/tt0325805/?ref_=fn_al_tt_1

le film :Les associés 
voilà le bug détaillé ;)

**Comment by djoole** [comment]
Normalement y a plus de souci avec Batman v Superman: Dawn of Justice.
Ca venait du fait que title était en unicode et newTitle en str
Pour remédier à ça j'ai viré les .encode('utf8') des retours de l'API Allocine.
Pour moi faudrait mettre du decode au contraire, mais je ne sais pas quel codec est utilisé par l'API.

@D4rk56 tu peux confirmer que ça roule?

@maxcore je vais tester les associés

**Comment by D4rk56** [comment]
Je te dis ça demain début d'après-midi @djoole

**Comment by D4rk56** [comment]
Voilà le resultat

### Logs:

```
07-28 13:18:53INFO[core.media.movie.searcher] Search for Batman v Superman: Dawn of Justice in DVD-Rip ignoring ETA
07-28 13:18:53DEBUG[                     t411] Searching T411 for batman v superman dawn of justice
07-28 13:18:53DEBUG[                     t411] Looking for French title of : batman v superman dawn of justice
07-28 13:18:53DEBUG[ato.core.helpers.encoding] Failed ss encoding char, force UTF8: 'latin-1' codec can't encode character u'\u2019' in position 59: ordinal not in range(256)
07-28 13:18:53DEBUG[                     t411] Allocine API found the french title : Batman v Superman : L?Aube de la Justice
07-28 13:18:53DEBUG[                     t411] Requesting alternative quality terms for : ['dvdrip']
07-28 13:18:53DEBUG[                     t411] Found alternative quality terms : ['dvdrip', '(dvd rip)']
07-28 13:18:53DEBUG[ato.core.helpers.encoding] Failed ss encoding char, force UTF8: 'latin-1' codec can't encode character u'\u2019' in position 101: ordinal not in range(256)
07-28 13:18:53DEBUG[ato.core.helpers.encoding] Failed ss encoding char, force UTF8: 'latin-1' codec can't encode character u'\u2019' in position 101: ordinal not in range(256)
07-28 13:18:53DEBUG[hpotato.core.plugins.base] Waiting for t411, 1 seconds
07-28 13:18:53INFO[hpotato.core.plugins.base] Opening url: get https://www.t411.io/torrents/search/?search=(batman%20v%20superman%20dawn%20of%20justice)%7C(Batman%20v%20Superman%20%20L?Aube%20de%20la%20Justice)%20dvdrip%7C(dvd%26rip), data: []
```

**Comment by djoole** [comment]
Bizarre, je resseraie ce soir mais je n'avais plus de souci...
J'ai l'impression que c'est un problème d'encoding peut être relatif à ton environnement..
De toute façon il il y a un autre souci : quand le titre que fournit CP contient des accents ils sont mal décodés. 
Et ça je ne sais pas si le provider peut y remédier de son côté...

**Comment by djoole** [comment]
@D4rk56 regarde, chez moi ça marche : 

```
07-28 22:36:49 INFO [core.media.movie.searcher] Search for Batman v Superman: Dawn of Justice in 1080p ignoring ETA
07-28 22:36:49 DEBUG [                     t411] Searching T411 for batman v superman dawn of justice
07-28 22:36:49 DEBUG [                     t411] Looking for French title of : batman v superman dawn of justice
07-28 22:36:49 DEBUG [                     t411] Allocine API found the french title : Batman v Superman : L’Aube de la Justice
07-28 22:36:49 DEBUG [                     t411] Requesting alternative quality terms for : ['1080p']
07-28 22:36:49 DEBUG [                     t411] Found alternative quality terms : ['1080p']
07-28 22:36:49 INFO [hpotato.core.plugins.base] Opening url: get https://www.t411.io/torrents/search/?search=(batman%20v%20superman%20dawn%20of%20justice)%7C(Batman%20v%20Superman%20%20L%E2%80%99Aube%20de%20la%20Justice)%201080p, data: []
07-28 22:36:50 DEBUG [hpotato.core.plugins.base] Setting cache 20ddd24a2f60e9b30761bd8e82548695
07-28 22:36:50 DEBUG [                     t411] Received data from T411
07-28 22:36:50 DEBUG [                     t411] Data is valid from T411
07-28 22:36:50 DEBUG [                     t411] No table results from T411
```

Mais je pense que c'est peut-être lié à la modif que j'ai faite là : https://github.com/djoole/couchpotato.provider.t411/commit/47efa88be07a519beeb1ec4746c06563122ca440

Peux-tu remettre comme avant et refaire l'essai et me dire si ça vient de là?
Moi en tout cas j'ai résolu les erreurs que je voyais dans mes logs en enlevant l'encodage du titre allociné...

**Comment by djoole** [comment]
Pour @maxcore 
J'ai ressayé avec Les Associés. Cette fois, et de façon générale, lorsque le titre original comporte des accents, c'est CP qui bugue.

J'ai rajouté un debug pour connaitre le type de chaine du titre passé au plugin par CP : 

```
07-28 23:48:28 DEBUG [                     t411] Searching T411 for les associes
07-28 23:48:28 DEBUG [                     t411] <type 'str'>

07-28 23:48:28 DEBUG [                     t411] Searching T411 for les associÃ©s
07-28 23:48:28 DEBUG [                     t411] <type 'unicode'>
```

Dans un 1er temps, CP passe un titre epuré de tout accent ou caractère bizarre (genre le : )
Cette chaine est encodée (type str)

Dans un 2ème temps, CP passe le titre original brut (avec accents et tout le toutim) sauf qu'il l'a décodé (type unicode), mais mal décodée!
Du coup le plugin ne peux plus rien en faire : il faudrait la rencoder avec le même codec qu'a utilisé CP, et la décoder avec le bon..

Je te conseille de passer un bug à Ruud burger...

**Comment by djoole** [comment]
@clement-escolano tu as peut-être une idée?

Je vois 2 problèmes résiduels concernant les accents : 
1. Lorsque le titre original comporte des accents, et que CP passe ce titre au plugin, il semble qu'il soit mal décodé lorsqu'il arrive dans le plugin
2. Lorsque le titre passé par CP n'a pas d'accent, mais que le titre FR est cherché via ton API Allocine, le titre FR remonté est mal décodé

**Comment by D4rk56** [comment]
Ha quel galère, le français.. 
J'essaie ça demain quand j'ai un moment @djoole

**Comment by maxcore** [comment]
@djoole 
si tu fais la meme chose que tu as faite avec hd-o ça le fait pareil ?

**Comment by djoole** [comment]
Non c'est pas le même problème.. sur HDO il suffisait de décoder le retour du site HDO qui contenait des entités HTML.

La le souci, c'est que CP et l'API Allocine fournisse au provider une chaine de caractère qui contient à la base des accents, mais décodée avec le mauvais codec, du coup, y a des caractères bizarres à la place des accents dans la chaine, et je ne peux (sais?) pas retrouver les caractères d'origine vu que la chaine est décodée..

**Comment by maxcore** [comment]
@djoole 
tu connais 
http://wiki.gromez.fr/dev/api/allocine_v3

et j'ai trouver ça

http://forum.phpfrance.com/php-debutant/api-allocine-t272921.html

?

**Comment by clement-escolano** [comment]
Coucou tout le monde !
Bon je suis un peu à court de temps en ce moment. 
Quand j'avais testé chez moi, ça marchait très bien :cry: 
Le plus simple ici je pense c'est de remplacer les accents par leur équivalent sans accent (é -> e, à -> a, etc) car t411 ne fait pas la distinction. Python et les encodages, c'est un vrai enfer !
Je regarderai ça à tête reposée plus tard.

**Comment by djoole** [comment]
@maxcore,
Merci pour les liens, je connaissais le 1er mais l'encart rouge explique qu'on doit maintenant signer les appels vers l'API, ce que fait l'API de @clement-escolano 
Je pense que le souci est coté allocine.

Donc la seule seule solution serait effectivement peut-être de remplacer les caractères accentués par des équivalences mais encore faut-il connaître la traduction à appliquer!

**Comment by djoole** [comment]
Hello, Je suis pas loin de la nuit blanche mais je crois que c'est tout bon!
En fait CP décode correctement le titre original lorsqu'il a des accents.. c'est la fonction CPLog qui a un pet au casque et et affiche mal les accents 99% du temps.

Bref, après une grosse prise de tête, je pense avoir réussi : l'API TMDB remonte bien le titre FR correspondant au titre original servi par CP. Je passe bien le titre FR (et l'original) encodé et échappé comme il faut à T411 pour qu'il retrouve ses petits.

Plus qu'à faire pareil pour HDO :)

Je clos cette issue. Si jamais il reste des cas particuliers, merci d'en ouvrir une nouvelle.

**Comment by maxcore** [comment]
@djoole coool j'ai hâte de tester ;)
