### ISSUE TITLE
Téléchargement erroné

### ISSUE THREAD

**Issue by jurnet** [djoole/couchpotato.provider.t411#15]
Bonjour le telechargement du fichier sur t411 est erroné avec le fork de sarahka et c'est pareil pour vous.
Avez vous trouvé une solution ?
Merci

**Comment by fana13** [comment]
Pour moi c'est pareil T411 ne fonctionne pas avec le nouveau fork de ruudburger repris par sarahka, et il n'a malheureusement pas repris les autres providers qui étaient présents comme FNT ou Libertalia (ou ajouter d'autres providers bluetigers, xthor...). C'est fort dommage, moi du coup je n'ai pas fait l'update je suis resté sur l'ancien fork...
Et puis j'ai pas l'impression que l'on peut communiquer avec sarahka (ou du moins je n'ai pas trouvé)

**Comment by jurnet** [comment]
Du coup si je comprends bien tu es sur une ancienne version master du fork de sarahka ? 

Et tu n'as pas de soucis avec T411 lors de tes downloads ?
Sinon tu t'y connais en dev python, ca te tenterais de faire des trucs ?

**Comment by fana13** [comment]
Ouais je suis sur l'ancienne version et tout tourne correctement HDO et T411 de Djoole et FNT et LTL aussi. Non par contre désolé mais en dev je suis une quiche !

**Comment by djoole** [comment]
Bonjour, je ne supporte que la version de Ruudburger désolé!
