### ISSUE TITLE
Problème avec la dernière version de couchpotato

### ISSUE THREAD

**Issue by floppy84** [djoole/couchpotato.provider.t411#17]
j'obtiens une erreure de ce genre dans la dernière version de couch :+1: 
-24 17:14:15
ERROR
[   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/opt/CouchPotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(_args, *_kwargs)
  File "/opt/CouchPotato/couchpotato/core/media/_base/providers/base.py", line 220, in search
    self._searchOnTitle(title, media, quality, results)
  File "/opt/CouchPotato/custom_plugins/t411/main.py", line 44, in _searchOnTitle
    for entry in output['torrents']:
KeyError: 'torrents'
encoding=UTF-8 debug=False args=['--quiet', '--daemon', '--pid_file=/home/osmc/.couchpotato.pid', '--data_dir=/opt/CouchPotato'] app_dir=/opt/CouchPotato data_dir=/opt/CouchPotato desktop=None options=Namespace(config_file='/opt/CouchPotato/settings.conf', console_log=False, daemon=True, data_dir='/opt/CouchPotato', debug=False, pid_file='/home/osmc/.couchpotato.pid', quiet=True)

**Comment by djoole** [comment]
Désolé mais tu dois utiliser un plugin qui n'est pas le mien.
Tu constateras [ici qu'en ligne 44](https://github.com/djoole/couchpotato.provider.t411/blob/master/t411/main.py#L44) il n'y a pas le code `for entry in output['torrents']:`, ni même ailleurs dans le script.
