### ISSUE TITLE
FnT.nu ?

### ISSUE THREAD

**Issue by ghost** [djoole/couchpotato.provider.t411#18]
Salut,
Etant donné que seul toi est actif concernant le developpement de plugins CP français, peut être aurais tu été intéressé pour développer un plug pour le fameux tracker FnT.nu ? Etant moi même utilisateur de FnT ET CP et n'étant sûrement pas le seul, est-ce que je peux te donner un éventuel coup de main concernant le site/les flux si tu n'es pas déjà membre ou à défaut, peux tu me donner quelqu'un vers qui m'orienter si l'idée ne te paraissais pas pertinente ?

Merci a toi :+1:

**Comment by djoole** [comment]
C'est dans ma todo liste pour cet hiver :)

**Comment by ghost** [comment]
C'est super, merci encore pour ton investissement ! :)

**Comment by Barracuda26** [comment]
Super merci Djoole :)

**Comment by ghost** [comment]
Pour en revenir à la version t411, j'ai des messages d'erreurs dans tous les sens : 

10-10 09:23:24 ERROR [   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/volume2/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/event.py", line 15, in runHandler
    return handler(_args, *_kwargs)
  File "/volume2/@appstore/couchpotatoserver/share/CouchPotatoServer/couchpotato/core/media/_base/providers/base.py", line 233, in search
    self._searchOnTitle(title, media, quality, results)
  File "/usr/local/couchpotatoserver/var/custom_plugins/t411/main.py", line 44, in _searchOnTitle
    for entry in output['torrents']:
KeyError: 'torrents'
encoding=UTF-8 debug=False args=['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf'] app_dir=/usr/local/couchpotatoserver/share/CouchPotatoServer data_dir=/usr/local/couchpotatoserver/var desktop=None options=Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)  

```

Une idée ?
```

**Comment by djoole** [comment]
Regarde la #17 dernier comment... Tu n'utilises pas mon plugin donc je peux rien pour toi :)
