### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u0153'

### ISSUE THREAD

**Issue by saillmone** [djoole/couchpotato.provider.t411#19]
Hello djoole,

Sur la recherche "Connasse, princesse des cœurs", le œ fait tout péter ! Je sais que tu as déjà eu des soucis avec l'encodage des caractères... mille excuses, en voilà un autre ;-)
Merci pour tout le taf.

`ERROR [   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/opt/CouchPotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/opt/CouchPotato/couchpotato/core/media/_base/providers/base.py", line 220, in search
    self._searchOnTitle(title, media, quality, results)
  File "/opt/CouchPotato/custom_plugins/t411/main.py", line 87, in _searchOnTitle
    request = urllib2.quote(request.encode('iso-8859-1'))
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u0153' in position 58: ordinal not in range(256)
encoding=UTF-8 debug=False args=['--quiet', '--daemon', '--pid_file=/home/pi/.couchpotato.pid', '--data_dir=/opt/CouchPotato'] app_dir=/opt/CouchPotato data_dir=/opt/CouchPotato desktop=None options=Namespace(config_file='/opt/CouchPotato/settings.conf', console_log=False, daemon=True, data_dir='/opt/CouchPotato', debug=False, pid_file='/home/pi/.couchpotato.pid', quiet=True)`

**Comment by djoole** [comment]
Désolé, je ne vais pas (plus) avoir le temps de passer des heures à résoudre un cas très particulier.
Je t'invite à récupérer le film en manuel (j'imagine que c'est fait depuis le temps :) )

**Comment by geraldgg** [comment]
J'ai fait un fix sur mon fork, qui peut peut-être t'intéresser. https://github.com/geraldgg/CouchPotato-t411-custom_plugin/commit/87e270719ffcff8eb5fc11ecfee2611a7eca9923

**Comment by djoole** [comment]
Merci, j'ai vite fait essayé, mais ça plante toujours chez moi : 

```
04-04 11:55:24 DEBUG [                     t411] Looking on TMDB for French title of : connasse, princesse des cœurs
04-04 11:55:24 INFO [hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&language=fr&query=connasse,%20princesse%20des%20c%C5%93urs, data: []
04-04 11:55:24 DEBUG [hpotato.core.plugins.base] Setting cache 183caa88ce88c15e329cdac2394abdf4
04-04 11:55:24 DEBUG [                     t411] TMDB report identical FR and original title
04-04 11:55:24 ERROR [   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/usr/local/couchpotato/couchpotato/core/event.py", line 15, in runHandler
    return handler(*args, **kwargs)
  File "/usr/local/couchpotato/couchpotato/core/media/_base/providers/base.py", line 233, in search
    self._searchOnTitle(title, media, quality, results)
  File "/usr/local/couchpotato_config/custom_plugins/t411/main.py", line 87, in _searchOnTitle
    request = urllib2.quote(self.getEncodedString(request, 'iso-8859-1'))
  File "/usr/local/couchpotato_config/custom_plugins/t411/main.py", line 226, in getEncodedString
    return s.encode(encoding)
UnicodeEncodeError: 'latin-1' codec can't encode character u'\u0153' in position 25: ordinal not in range(256)
encoding=UTF-8 debug=True args=['--daemon', '--data_dir', '/usr/local/couchpotato_config'] app_dir=/usr/local/couchpotato data_dir=/usr/local/couchpotato_config desktop=None options=Namespace(config_file='/usr/local/couchpotato_config/settings.conf', console_log=False, daemon=True, data_dir='/usr/local/couchpotato_config', debug=False, pid_file='/usr/local/couchpotato_config/couchpotato.pid', quiet=False) 
04-04 11:55:24 DEBUG [core.media.movie.searcher] Nothing found for Connasse, Princesse des cœurs in 1080p
```

**Comment by geraldgg** [comment]
Ah oui, je vois. C'est du latin-1. Je regarderai ce soir si je trouve quelque chose.

**Comment by geraldgg** [comment]
En passant en utf8 par défaut, ça semble résoudre le problème, on n'est plus embêté par des characters sets trop petits;
https://github.com/geraldgg/CouchPotato-t411-custom_plugin/commit/3a3866bdfa237a9cc3b7696206a7c451fb93a2a1
