### ISSUE TITLE
Couchpotato n'a plus les caractéristiques des releases de T411

### ISSUE THREAD

**Issue by turbalf** [djoole/couchpotato.provider.t411#20]
Salut Djoole,
Tout d'abord merci pour ce plugin qui sauve la vie des francophones !
Je ne sais pas s'ils sont liés mais j'ai deux problèmes : depuis que j'ai remplacé le plugin par la nouvelle version, CP n'affiche plus la taille et l'âge des releases qu'il trouve (cf prise d'écran jointe).
Je ne sais pas si c'est lié, mais il ne me trouve plus les full bluray sur le site, je vois dans les logs qu'il élimine des releases à cause de leur taille mais de toutes façons leurs noms ne correspondent pas au releases full bluray qu'on trouve en allant directement sur le site.
J'ai tenté le fork de sharakha qui intègre directement T411, là j'ai bien les infos de taille et d'âge mais idem, il me snobe les releases full bluray, et pourtant j'ai viré tous les filtres pour être sûr !
Voilà, au secours !

![t411](https://cloud.githubusercontent.com/assets/12201422/10887116/ae0c0a7a-8185-11e5-8a4f-fe6fa771b0a0.jpg)

**Comment by foozalex** [comment]
Chez moi avec la dernière version j'ai bien la taille par contre pour l'âge, cette petite modification permet de l'avoir : 

```
diff --git a/t411/main.py b/t411/main.py
index 9f18453..64a66b5 100644
--- a/t411/main.py
+++ b/t411/main.py
@@ -121,6 +121,7 @@ class t411(TorrentProvider, MovieProvider):
                         'name': replaceTitle(release_name, title, newTitle),
                         'url': self.urls['download'] % idt,
                         'detail_url': self.urls['detail'] % idt,
+                       'age':age,
                         'size': self.parseSize(str(result.findAll('td')[5].text)),
                         'seeders': result.findAll('td')[7].text,
                         'leechers': result.findAll('td')[8].text,
```

**Comment by turbalf** [comment]
merci pour ta réponse, du coup entre temps j'ai mis un autre plugin (cocazoulou) et ça marche !

**Comment by djoole** [comment]
Bonjour,

J'ai bien la taille que s'affiche, mais effectivement pas l'âge.
Je vais regarder ça.
@CrazyTuc, effectivement en rajoutant `'age':age`, ça devrait le faire car j'ai définit plus haut dans le code la valeur de age : `result.findAll('td')[4].text,`
Par contre on récupère du texte du genre "1 mois", "2 ans" etc. Je pense pas que CP va aimer..

Pour le full bluray @turbalf, il te suffit de customiser les tailles acceptables pour chaque qualité (20000-60000 chez moi)

**Comment by djoole** [comment]
Bon ben ça marche, ça dérange pas CP qu'il y ait "mois" ou "an"

**Comment by lscalese** [comment]
Bonjour,
Est-ce que j'ai mal compris ou est-ce que l'on utilise pas l'api t411 (https://api.t411.ch/) dans le programme?   J'ai l'impression que l'on se complique la vie à faire des recherche dans le contenu html récupéré.
Merci.

**Comment by djoole** [comment]
Yes, à l'époque ou j'ai écrit le plugin, l'API n'existait pas, ou tout du moins je ne connaissais pas son existence, pas faute d'avoir cherché.
J'ai le #7 pour me rappeler que si un jour je m'ennuie (chose qui n'arrivera jamais) je pourrai récrire le code en utilisant l'API.

**Comment by lscalese** [comment]
C'est courageux de l'avoir fais sans l'API.  Moi je n'aurais pas eu le courage de me lancer.
Je dois bientôt faire un peu mon apprentissage sur "Node.js", Il est possible que mon programme d'essais soit un "Torznab" pour t411. Si c'est le cas je viendrai mettre un message ici.
