### ISSUE TITLE
Installer le module python ast

### ISSUE THREAD

**Issue by gogui51** [djoole/couchpotato.provider.t411#22]
Bonjour,
je fais suite à l'issue précédente : https://github.com/djoole/couchpotato.provider.t411/issues/21

j'étais en congés et j'ai pas eu le temps de poser ma question : comment installer le module python ast que tu mentionnes en fin de topic ?

Google ne m'a pas aidé sur ce coup :(

Merci de ton aide.

**Comment by djoole** [comment]
Tu peux faire des comment sur une issue fermée, pas besoin d'en créer une nouvelle :)

AST est un module intégré à l'installation de base de python, il ne s'installe pas indépendamment.
Du coup je sais pas trop comment t'aider à part te conseiller une reinstall propre de python.

**Comment by gogui51** [comment]
Arf, désolé je ne savais pas qu'on pouvais répondre sur une issue fermée :)

Ok, ce qui est bizarre c'est que si ce n'est pas intégré à OSMC alors je ne sais pas comment l'installer... Bon ben je ferme le topic directement.

Merci de ton aide

**Comment by djoole** [comment]
Direction forum OSMC où je ne doute pas que tu trouveras de l'aide pour t'aider à installer manuellement une version complète de python ;-)
Je pense que la version que tu as actuellement doit être une version "light"
