### ISSUE TITLE
Provider Introuvable dans CP

### ISSUE THREAD

**Issue by Tobear91** [djoole/couchpotato.provider.t411#24]
Hello,

Petit soucis pour afficher le provider T411 dans mon CP. Je télécharge les sources réalisé cette commande pour déplacer le dossier : 

**mv /volume1/video/t411 /usr/local/couchpotatoserver/var/custom_plugins/**

Mais le provider n'apparait pas dans la liste. Une petite idée.
Je suis sur un DS216play de chez Syno. Est ce qu'il peut y avoir une incompatibilité ?

Merci

**Comment by djoole** [comment]
Pour savoir ce qui ne va pas il faut que tu postes les longs de démarrage
de CP en mode DEBUG

**Comment by danylich** [comment]
Regarde les droits de tes fichiers. Perso je mets 755 sur le dossier t411 et sur tous les fichiers fils.

**Comment by djoole** [comment]
Pas de logs, je suppose que le problème est résolu
