### ISSUE TITLE
Line 198 - list indices must be integers

### ISSUE THREAD

**Issue by pacofq** [djoole/couchpotato.provider.t411#25]
### Logs:

```
03-20 16:59:24 ERROR [                     t411] Failed to parse TMDB API: Traceback (most recent call last):
  File "/var/db/couchpotato/custom_plugins/t411/main.py", line 198, in getFrenchTitle
    if data['results'] != None:
TypeError: list indices must be integers, not str
```

**Comment by pacofq** [comment]
that's the error I get evrytime CP searches for a movie in t411

Thanks 4 your help

**Comment by djoole** [comment]
Post debug logs please

**Comment by tcheronneau** [comment]
Hello,
I'm having the same issue. 
So I wanted to add debug log (and do a restart of couch as required). 
But after the restart the problem was solved. 

So this issue appends when you add a movie in your wanted but it is solved after a restart (don't really understand why) but you can reproduce the error I think. 

The debug log don't tell anything else than the logs from @pacofq. 

Thanks for you help.

**Comment by djoole** [comment]
OK, I also got the error, maybe a change in TMDB API, I'll look into it when I get the chance.

**Comment by djoole** [comment]
```
04-04 10:20:44 INFO [hpotato.core.plugins.base] Disabled calls to api.themoviedb.org for 15 minutes because so many failed requests.
```

This is what's happening just before the error. It means CP has prevented the plugin to access TMDB.

On my logs I have a lot of these : 

```
04-04 10:13:05 DEBUG ^[[36m[providers.info.themoviedb] Searching for movie: tell 2014^[[0m
04-04 10:13:05 INFO ^[[0m[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&search_type=phrase&query=tell&year=2014, data: []^[[0m
04-04 10:13:06 DEBUG ^[[36m[providers.info.themoviedb] Movie not found: search/movie, search_type=phrase&query=tell&year=2014^[[0m
```

For movies which are not even in my CP!

And then, it changes for this : 

```
04-04 10:13:08 DEBUG ^[[36m[providers.info.themoviedb] Searching for movie: forsaken 2015^[[0m
04-04 10:13:08 INFO ^[[36m[hpotato.core.plugins.base] Disabled calls to api.themoviedb.org for 15 minutes because so many failed requests.^[[0m
04-04 10:13:08 DEBUG ^[[36m[providers.info.themoviedb] Movie not found: search/movie, search_type=phrase&query=forsaken&year=2015^[[0m
```

So, here is how I interpret this : 

CP periodically looks on TMDB API for movies info (maybe bluray charts movies?).
Sometimes, for unknown reason, TMDB API doesn't respond (movie not found).
After a few fails, CP consider TMDB down, and disable it for 15 minutes.
As my plugin also use TMDB to get french title, I'm victim of that.

But anyway, after 15 min (or a CP restart indeed @tomtom54) it should work again, so no big deal.
