### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by scoony** [djoole/couchpotato.provider.t411#30]
07-29 18:26:25 ERROR[hpotato.core.plugins.base] Failed opening url in t411: https://www.t411.ch/users/login/ Traceback (most recent call last): HTTPError: 403 Client Error: Forbidden for url: https://www.t411.ch/users/login/
07-29 18:26:25 ERROR[edia._base.providers.base] Failed to login t411: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/media/_base/providers/base.py", line 163, in login output = self.urlopen(self.urls['login'], data = self.getLoginParams()) File "/opt/couchpotato/couchpotato/core/plugins/base.py", line 226, in urlopen response.raise_for_status() File "/opt/couchpotato/libs/requests/models.py", line 837, in raise_for_status raise HTTPError(http_error_msg, response=self) HTTPError: 403 Client Error: Forbidden for url: https://www.t411.ch/users/login/
07-29 18:26:25 ERROR[edia._base.providers.base] Failed to login to: t411

**Comment by djoole** [comment]
Bonjour,
Je ne peux pas faire grand chose avec ce rapport.
C'est le site qui renvoie une erreur 403 (accès refusé).
Probablement car les infos d'authentification sont erronées ou que le site rencontrait des difficultés temporaires.
Je n'ai pas ce souci.
Si vous l'avez toujours, merci de poster l'intégralité des logs en niveau DEBUG.

**Comment by djoole** [comment]
Pas de réponse.
