### ISSUE TITLE
Erreur lors du téléchargement du torrent

### ISSUE THREAD

**Issue by sy-per** [djoole/couchpotato.provider.t411#32]
Bonjour , j'ai cette erreur lors de la récupération du torrent : 

> [ couchpotato.core.event] Error in event "download", that wasn't caught: Traceback (most recent call last): File "/opt/couchpotato/couchpotato/core/event.py", line 15, in runHandler return handler(_args, *_kwargs) File "/opt/couchpotato/couchpotato/core/_base/downloader/main.py", line 73, in _download return self.download(data = data, media = media, filedata = filedata) File "/opt/couchpotato/couchpotato/core/downloaders/transmission.py", line 70, in download if os.path.isdir(self.conf('directory')): File "/usr/lib/python2.7/genericpath.py", line 41, in isdir st = os.stat(s) UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 45: ordinal not in range(128) encoding=UTF-8 debug=False args=['--quiet', '--daemon', '--pid_file=/var/run/couchpotato/couchpotato.pid', '--data_dir=/home/couchpotato/.couchpotato'] app_dir=/opt/couchpotato data_dir=/home/couchpotato/.couchpotato desktop=None options=Namespace(config_file='/home/couchpotato/.couchpotato/settings.conf', console_log=False, daemon=True, data_dir='/home/couchpotato/.couchpotato', debug=False, pid_file='/var/run/couchpotato/couchpotato.pid', quiet=True)

Je pensait que sa venait de mon logiciel de téléchargement mais en changeant c'est pareil ...

Merci de votre aide

**Comment by djoole** [comment]
Cette seule ligne ne réfère jamais au provider.. du coup je ne peux rien faire pour toi.
Peux tu poster l'intégralité des logs en mode debug?

**Comment by sy-per** [comment]
> [.downloaders.transmission] response: {"tag": 0, "arguments": {"idle-seeding-limit": 30, "alt-speed-time-end": 1020, "cache-size-mb": 4, "blocklist-url": "http://update.transmissionbt.com/level1.gz", "alt-speed-time-begin": 540, "speed-limit-up-enabled": false, "queue-stalled-enabled": true, "download-queue-size": 5, "rename-partial-files": true, "script-torrent-done-filename": "", "seedRatioLimited": false, "idle-seeding-limit-enabled": false, "peer-limit-per-torrent": 60, "incomplete-dir": "/media/39a9b0b4-d717-4f87-bbcd-def990b6b495/T\u00e9l\u00e9chargement//incomplet", "rpc-version": 15, "blocklist-enabled": false, "speed-limit-down-enabled": false, "download-queue-enabled": true, "seedRatioLimit": 4, "encryption": "preferred", "lpd-enabled": false, "alt-speed-down": 50, "download-dir": "/media/39a9b0b4-d717-4f87-bbcd-def990b6b495/T\u00e9l\u00e9chargement/films", "alt-speed-enabled": false, "version": "2.82 (14160)", "blocklist-size": 0, "units": {"speed-bytes": 1000, "memory-units": ["KiB", "MiB", "GiB", "TiB"], "size-bytes": 1000, "speed-units": ["kB/s", "MB/s", "GB/s", "TB/s"], "memory-bytes": 1024, "size-units": ["kB", "MB", "GB", "TB"]}, "queue-stalled-minutes": 30, "seed-queue-size": 10, "dht-enabled": true, "peer-limit-global": 240, "pex-enabled": true, "download-dir-free-space": 925646790656, "alt-speed-up": 50, "script-torrent-done-enabled": false, "peer-port-random-on-start": false, "rpc-version-minimum": 1, "peer-port": 51413, "start-added-torrents": true, "port-forwarding-enabled": true, "trash-original-torrent-files": false, "speed-limit-up": 100, "speed-limit-down": 100, "alt-speed-time-enabled": false, "config-dir": "/var/lib/transmission-daemon/info", "incomplete-dir-enabled": true, "utp-enabled": true, "alt-speed-time-day": 127, "seed-queue-enabled": false}, "result": "success"}

Voila la ligne en mode debug et du coup j'ai trouvé mon erreur, désoler de t'avoir dérangé ce sont uniquement les accents du dossier de téléchargement qui foutent la merde.
