### ISSUE TITLE
No data fetch, but there are some

### ISSUE THREAD

**Issue by ghost** [djoole/couchpotato.provider.t411#34]
Here is the example:
CP version 4a0999d9

For this movie:
https://www.t411.ch/torrents/search/?search=%28un%20homme%20a%20la%20hauteur%29%7C%28un%20homme%20%E0%20la%20hauteur%29%20720p

10-17 03:22:42 INFO [hpotato.core.plugins.base] Opening url: get https://www.t411.ch/torrents/search/?search=un%20homme%20%E0%20la%20hauteur%20brrip%7Cbdrip%7Chdtv%7Chdrip%7C(br%26rip), data: []

**Comment by djoole** [comment]
Sorry no more time to solve a problem concerning only one movie. Please take it manually.
