### ISSUE TITLE
Could not login since the domain has change to .li

### ISSUE THREAD

**Issue by ghost** [djoole/couchpotato.provider.t411#35]
Hello,

We can't login into t411 since the domain as migrated from t411.ch to t411.li.

**Comment by Djedje93270** [comment]
For me CP login to t411 but no finilize research:

Opening url: get https://www.t411.ch/torrents/search/?search=%28finding%20dory%29%7C%28le%20monde%20de%20dory%29%20720p, data: []

End not continue...

**Comment by ghost** [comment]
Yes, that's exactly the problem I have

**Comment by djoole** [comment]
Done

https://github.com/djoole/couchpotato.provider.t411/commit/39207f05ca2910084110557821140d6d5542521f
