### ISSUE TITLE
Je ne vois pas le plugin dans l'interface et fichier torrent invalide

### ISSUE THREAD

**Issue by threnard** [djoole/couchpotato.provider.t411#36]
Bonjour,
Je n'arrive pas à installer le "searcher" pour t411 correctement. Je ne le vois pas apparaitre dans les "searchers".
J'ai dézippé le folder et déplacer dans /usr/local/couchpotatoserver/var/custom_plugins/
J'ai vérifié les droits sur le folder et les fichiers.

Je suis sur un Synology. J'utilise le paquet CouchPotato :
Version 89fd4e11 (24/01/2016 à 10:42:44)
masterID 10351

Ce qui est étrange, c'est que j'ai bien une entrée [t411] dans le fichier settings.conf.
J'ai donc renseigné à la main mon login / mot de passe t411 et j'ai mis enabled = True.
Je vois dans les logs que des choses se passent : 

[hpotato.core.plugins.base] Opening url: get http://www.t411.li/torrents/download/?id=5495692, data: []
[tato.core.plugins.release] Snatched "The Revenant 2015 FRENCH BluRay 1080p x264-HD Workshop": The Revenant (2015) in 1080p from t411
 [                     t411] result : name=the.revenant.2015.multi..1080p.bluray.x264-crocopik, detail_url=https://www.t411.li/torrents/?id=5514448
logs/CouchPotato.log.1:11-26 18:18:50 INFO [edia._base.providers.base] Found: score(134) on t411: the.revenant.2015.multi..1080p.bluray.x264-crocopik
logs/CouchPotato.log.1:11-26 18:18:51 DEBUG [                     t411] result : name=The.Revenant.2015.1080p.HDLight.Truefrench.DTS.H264~Xantar, detail_url=https://www.t411.li/torrents/?id=5515915

**Par contre :
- Je n'ai pas la conf du plugin dans l'interface
- Et j'ai une erreur dans Download station. Si je regarde le fichier torrent téléchargé, c'est en fait, j'ai l'impression, la page d'accueil de t411 (HTML), donc pas le fichier torrent...**

Par avance, merci pour l'aide.

**Comment by djoole** [comment]
Vraiment bizarre...
Le provider est correctement installé vu qu'on le voit bosser dans les logs..
Après je ne connais pas la version CP fournie par Syno, il y a peut-être des modifications par rapport à la version originale.
Mon provider n'est supporté que pour la version de Ruudburger : https://github.com/CouchPotato/CouchPotatoServer

Je peux pas faire grand chose pour toi du coup..

Je peux te mettre le contenu du fichier de config comme ça au pire tu le fais manuellement, t'as pas tant besoin de l'interface que ça en fait..
```
[t411]
username = myusername
seed_time = 40
extra_score = 30
enabled = 1
seed_ratio = 1
password = mypassword
ignore_year = 0
```

**Comment by djoole** [comment]
Désolé, je me rends compte que je n'ai pas répondu à ton problème principal.
Le fait que tu te retrouves avec un fichier .torrent qui contient le code HTML de la page d'accueil du site est à 99,99% le fait que le login/password mis dans le fichier n'est pas le bon.
Check again. Le mot de passe est en clair. Il me semblait avoir eu un souci avec les caractères type "*", mais je sais plus si c'était coté t411 ou coté CP.. donc essaye peut-être avec un mdp plus simple.

**Comment by threnard** [comment]
Bonjour djoole,
Je te remercie pour tes réponses rapides ! Bizaremment désormais ca marche. La seule chose que je vois c'est un redémarrage du NAS (et donc pas uniquement du paquet)...
Bref mes 1ers download t411 via CP fonctionnent !
Merci pour ton boulot, très utile cet addon (la demande peut être fermée) !
