### ISSUE TITLE
t411 not showing in the searcher / torrent_providers

### ISSUE THREAD

**Issue by nicecube** [djoole/couchpotato.provider.t411#37]
Bonjour, j'ai installé le plugin dans CouchPotato 
C:\Users\Nicecube\AppData\Roaming\CouchPotato\custom_plugins

custom_plugins:
t411\
t411\__init__.py
t411\__init__.pyc
t411\main.py
t411\main.pyc
__init__.py

Quand je vais dans la section Searcher je ne voie pas T411 même après un redémarrage de CouchPotato, pouvez vous m'aider

**Comment by julienfroidefond** [comment]
+1

**Comment by mogs31** [comment]
même chose ici ! 
Version b538f9a0 (21/12/2016 à 19:25:09) on debian8

--> Ok apres avoir vidé le cache sous chrome 👍

**Comment by acamilleri** [comment]
J'ai téléchargé le dossier, j'ai été dans Couchpotato -> About
J'ai noté le dossier qui était dans "Directories".
-> Pour moi: `/home/krysenn/.couchpotato`
J'ai copié le dossier T411 dans le dossier présent dans `/home/krysenn/.couchpotato`

J'ai redémarré Couchpotato, j'ai vidé mon cache et j'ai bien T411 qui s'affiche.

**Comment by djoole** [comment]
@nicecube poste les logs en debug

**Comment by zogtar** [comment]
+1
Bonjour,
T411 ne s'affiche pas dans la page "searcher"  je pense depuis le changement du plugin lié au passage de DNS .ch to .li

j'ai copié le répertoire t411 dans custom_plugins et suivi les conseils : vérification des répertoires et vidage du cache navigateur. Ca ne fonctionne pas avec Firefox et IE.
Après vérification des logs, je ne trouve pas la ligne "loaded custom_plugin : t411"

J'ai ensuite fait la même opération pour le plugin cpasbien afin de diagnostiquer le bug et là aucun problème.
En regardant de nouveau les logs, la ligne "loaded custom_plugin : cpasbien" est elle bien présente et dans le menue "searcher" cpasbien l'est également.

Version    3.0.1
Updater    desktop

Le log couchpotato est attaché.
1er démarrage avec seulement le plugin t411 et second démarrage avec T411 et cpasbien.
[CouchPotato.log.txt](https://github.com/djoole/couchpotato.provider.t411/files/736792/CouchPotato.log.txt)

**Comment by djoole** [comment]
Poste les logs en niveau de bug sinon je verrai pas pourquoi le plugin se charge pas.

**Comment by zogtar** [comment]
Oui, pardon.
Les voici

### Steps to reproduce:
1. Après un restart de couchpotato

### Information:
Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: desktop: 3.0.1
Running on: ...

### Logs:
```
01-31 21:13:53 DEBUG [  couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 164, in loadModule
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\importhelper\__init__.py", line 37, in import_module
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\custom_plugins\t411\__init__.py", line 2, in <module>
ImportError: No module named updater
 
```

**Comment by djoole** [comment]
Je pense que la version de ton plugin est obsolète... Le logs montre qu'en ligne 2 du __init__.py ça veut charger un module nommé "updater".
La ligne 2 du script est vide.
Fais un git pull, et essaie encore.
Si ça résout pas le problème, copie-moi le contenu de ton fichier "C:\Users\htpc\AppData\Roaming\CouchPotato\custom_plugins\t411\__init__.py"

Et vire aussi les fichiers .pyc on sait jamais

**Comment by zogtar** [comment]
J'ai supprimé les 4 fichiers et récupéré les dernières versions des fichiers ("Download ZIP") et voici le log maintenant après un restart.
Par contre quand je vois dans le init.py un lien vers t411 avec le domain en .ch : 'description': 'See <a href="https://www.t411.ch/">T411</a>',
je me demande si j'ai bien le bon fichier ... est-ce normal ?
En pièce jointe tu trouvera ce fichier init.py (j'ai ajouté l'extension txt pour l'upload sur le post)
[__init__.txt](https://github.com/djoole/couchpotato.provider.t411/files/748876/__init__.txt)

2-02 21:10:48DEBUG[  couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 164, in loadModule
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\importhelper\__init__.py", line 37, in import_module
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\custom_plugins\t411\__init__.py", line 1, in <module>
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\custom_plugins\t411\main.py", line 16, in <module>
ImportError: No module named ast

**Comment by djoole** [comment]
On avance, tu avais donc bien un souci de sources.

Maintenant ton problème c'est que ton install ne dispose pas de la
librairie AST. C'est une librairie qui est installée de base avec Python.
Je te conseille de le réinstaller!

**Comment by zogtar** [comment]
J'ai désinstallé python puis réinstallé la v2.7.13.
La commande "import ast" depuis la console python fonctionne.
Alors qu'avant elle était en erreur.

Voici les logs CP, toujours pareil. CP ne voit pas le module ast.
02-05 14:55:58DEBUG[  couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\couchpotato\core\loader.py", line 164, in loadModule
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\application\CouchPotato-3.0.1.win32\libs\importhelper\__init__.py", line 37, in import_module
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\custom_plugins\t411\__init__.py", line 1, in <module>
  File "C:\Users\htpc\AppData\Roaming\CouchPotato\custom_plugins\t411\main.py", line 16, in <module>
ImportError: No module named ast

As-tu une idée ?

**Comment by djoole** [comment]
Oui une dernière : ta distrib couchpotato vient avec une version portable de python, ce qui fait qu'il n'utilise pas le python que tu viens fraîchement d'installer. 

Ce n'est qu'une hypothèse, et après ca je sera sec.

**Comment by zogtar** [comment]
ça fonctionne, merci beaucoup pour le temps passé.
Ce n'était donc pas un bug du plugin t411.

Avant d'y arriver j'ai fais de nombreux tests qui n'ont rien donnés, j'ai donc fini par tout reprendre.

pour cela : 
désinstallation de python puis
- installation de python 2.7.10 32 bit (avant j'étais sur du 64bit en v2.7.13)
- installation de pywin 32 bit
- installation de couchpotato "depuis les sources" plutôt que depuis l'excecutable.

**Comment by djoole** [comment]
Parfait!
