### ISSUE TITLE
Erreur GetFrenchTitle

### ISSUE THREAD

**Issue by Viand0x** [djoole/couchpotato.provider.t411#38]
Bonjour, 
J'ai dans mes logs une erreur qui indique une variable qui n'est pas du bon type.
`[ t411] Failed to parse TMDB API: Traceback (most recent call last): File "/config/data/custom_plugins/t411/main.py", line 200, in getFrenchTitle if data['results'] != None: TypeError: list indices must be integers, not str `

Version couchpotato : b538f9a0 (21/12/2016 à 19:25:09)

Je ne connais pas python donc incapable de résoudre le problème...

**Comment by djoole** [comment]
doublon https://github.com/djoole/couchpotato.provider.t411/issues/25#issuecomment-205199436
