### ISSUE TITLE
Failed to login to t411 api

### ISSUE THREAD

**Issue by Djedje93270** [djoole/couchpotato.provider.t411#39]
Salut, j'ai un problème avec couchpotato qui me dit Failed to login to t411 api, du coup il prend le torrent via l'url normale et quand le torrent arrive dans download station sur mon synology, il me dit fichier torrent invalide.

**Comment by djoole** [comment]
J'ai besoin des logs en debug

**Comment by hexleyOlive** [comment]
J'ai la même erreur, ci-dessous les logs debug

04-29 13:49:52
INFO
[hpotato.core.plugins.base] Opening url: post https://api.t411.ai/auth, data: ['username', 'password']
04-29 13:49:52
DEBUG
[o.core.notifications.core] Cleaning messages
04-29 13:49:52
DEBUG
[o.core.notifications.core] Done cleaning messages
04-29 13:49:52
DEBUG
[hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last):
TypeError: __str__ returned non-string (type SysCallError)
04-29 13:49:52
ERROR
[edia._base.providers.base] Failed to login to: t411

**Comment by djoole** [comment]
Ton mot de passe disposé de caractères complexes? Si oui je te conseille de le modifier par un plus simple (chiffres et lettres seulement) et refaire le test. 
Sinon je vois pas.

**Comment by hexleyOlive** [comment]
J'ai trouvé aujourd'hui, le problème venait de OpenSSL. Après mise à jour Python + OpenSSL tout va bien.
Merci pour la réponse.
