### ISSUE TITLE
Impossible d'avoir une release multi et truefrench

### ISSUE THREAD

**Issue by PPACI** [djoole/couchpotato.provider.t411#40]
https://github.com/djoole/couchpotato.provider.t411/blob/master/t411/main.py#L116-L117

Ces lignes empêchent CP de rechecher le mot truefrench explicitement.
Or une release peut être multi EN-VFQ ou EN-VFF. Il est alors impossible pour CP de faire la différence.

Le fait d'enlever french et truefrench de la release si le mot multi est présent devrait être une option.
Je travail sur un fix, je ferai un pull request par la suite.

Merci de ton travail !

**Comment by djoole** [comment]
J'avais mis ces lignes car j'ai "french" en mot-clé interdit dans CP!
C'est une bonne idée de le mettre en option pour ceux qui ne sont pas dans mon cas!
