### ISSUE TITLE
UnboundLocalError: local variable 'res' referenced before assignment`

### ISSUE THREAD

**Issue by Surfoo** [djoole/couchpotato.provider.t411#47]
I found this error in the log file : 

`[ t411] Failed to parse TMDB API: Traceback (most recent call last): File "/var/opt/couchpotato/custom_plugins/t411/main.py", line 208, in getFrenchTitle frTitle = res['title'].lower() UnboundLocalError: local variable 'res' referenced before assignment`

**Comment by djoole** [comment]
I need you to give the full context in order to reproduce. 
And DEBUG logs. 
And be sure to be on the latest version of the plugin.
